# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-16 21:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
